# docker-compose.yml لمدير الاستثمار العقاري

version: '3.8'

services:
  # قاعدة البيانات PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: estate-management-db
    environment:
      POSTGRES_DB: estate_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - estate-network

  # Redis للتخزين المؤقت
  redis:
    image: redis:7-alpine
    container_name: estate-management-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - estate-network

  # التطبيق الرئيسي
  app:
    build: .
    container_name: estate-management-app
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres123@postgres:5432/estate_management
      - JWT_SECRET=estate-management-development-secret-key
      - REDIS_URL=redis://redis:6379
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - estate-network
    command: npm run dev

  # Nginx كـ reverse proxy
  nginx:
    image: nginx:alpine
    container_name: estate-management-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - estate-network

volumes:
  postgres_data:
  redis_data:

networks:
  estate-network:
    driver: bridge