# Kubernetes Deployment لمدير الاستثمار العقاري

apiVersion: v1
kind: Namespace
metadata:
  name: estate-management
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: estate-management-config
  namespace: estate-management
data:
  NODE_ENV: "production"
  PORT: "3000"
  DEFAULT_PAGE_SIZE: "20"
  MAX_PAGE_SIZE: "100"
  DEFAULT_THEME: "light"
  DEFAULT_LANGUAGE: "ar"
  TZ: "Africa/Cairo"
---
apiVersion: v1
kind: Secret
metadata:
  name: estate-management-secrets
  namespace: estate-management
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3VzZXJuYW1lOnBhc3N3b3JkQGhvc3Q6cG9ydC9kYXRhYmFzZQ==
  JWT_SECRET: eW91ci1zdXBlci1zZWN1cmUtcHJvZHVjdGlvbi1qd3Qtc2VjcmV0LWtleS1oZXJl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: estate-management-app
  namespace: estate-management
spec:
  replicas: 3
  selector:
    matchLabels:
      app: estate-management-app
  template:
    metadata:
      labels:
        app: estate-management-app
    spec:
      containers:
      - name: estate-management-app
        image: estate-management:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: estate-management-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: estate-management-config
              key: PORT
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: estate-management-secrets
              key: DATABASE_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: estate-management-secrets
              key: JWT_SECRET
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/monitoring/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/monitoring/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: estate-management-service
  namespace: estate-management
spec:
  selector:
    app: estate-management-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: estate-management-ingress
  namespace: estate-management
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - estate-management.your-domain.com
    secretName: estate-management-tls
  rules:
  - host: estate-management.your-domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: estate-management-service
            port:
              number: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: estate-management-hpa
  namespace: estate-management
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: estate-management-app
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80