[build]
  command = "PRISMA_SCHEMA_PATH=prisma/schema.postgres.prisma npx prisma generate && PRISMA_SCHEMA_PATH=prisma/schema.postgres.prisma npx prisma migrate deploy && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"