[build]
  command = "npx prisma generate --schema=prisma/schema.postgres.prisma && npx prisma migrate deploy --schema=prisma/schema.postgres.prisma && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"